### ISSUE TITLE
Anchore recorded feed_sync_start event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#10]
```
event:
  category: system
  details:
    sync_feed_types: all
  level: INFO
  message: Feed sync started
  resource:
    type: feeds
    user_id: admin
  source:
    base_url: http://engine-policy-engine:8228
    hostid: anchore-quickstart
    servicename: policy_engine
  timestamp: '2019-11-16T00:47:33.318993Z'
  type: feed_sync_start
notificationId: d5913e21-30e7-4390-8da5-778d1ca32a99
```
