### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#11]
```
event:
  category: user
  details:
    curr_eval:
      analysis_status: analyzed
      annotations: {}
      imageDigest: sha256:6ab380c5a5acf71c1b6660d645d2cd79cc8ce91b38e0352cbf9561e050427baf
    last_eval:
      analysis_status: analyzing
      annotations: {}
      imageDigest: sha256:6ab380c5a5acf71c1b6660d645d2cd79cc8ce91b38e0352cbf9561e050427baf
    subscription_type: analysis_update
  level: INFO
  message: Image successfully analyzed
  resource:
    id: docker.io/library/centos:latest
    type: image_tag
    user_id: admin
  source:
    base_url: http://engine-analyzer:8228
    hostid: anchore-quickstart
    servicename: analyzer
  timestamp: '2019-11-17T02:29:54.875397Z'
  type: analyze_image_success
notificationId: 83980a4f-2dde-463d-9c14-e77376668d43
```
