### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#12]
```
event:
  category: user
  details:
    curr_eval:
      analysis_status: analyzed
      annotations: {}
      imageDigest: sha256:134c7fe821b9d359490cd009ce7ca322453f4f2d018623f849e580a89a685e5d
    last_eval:
      analysis_status: analyzing
      annotations: {}
      imageDigest: sha256:134c7fe821b9d359490cd009ce7ca322453f4f2d018623f849e580a89a685e5d
    subscription_type: analysis_update
  level: INFO
  message: Image successfully analyzed
  resource:
    id: docker.io/library/ubuntu:latest
    type: image_tag
    user_id: admin
  source:
    base_url: http://engine-analyzer:8228
    hostid: anchore-quickstart
    servicename: analyzer
  timestamp: '2019-11-17T02:30:25.839388Z'
  type: analyze_image_success
notificationId: e2a8ad5a-32a3-4bd6-9649-1e8b6ff805fa
```
