### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#13]
```
event:
  category: user
  details:
    curr_eval:
      analysis_status: analyzed
      annotations: {}
      imageDigest: sha256:e4355b66995c96b4b468159fc5c7e3540fcef961189ca13fee877798649f531a
    last_eval:
      analysis_status: analyzing
      annotations: {}
      imageDigest: sha256:e4355b66995c96b4b468159fc5c7e3540fcef961189ca13fee877798649f531a
    subscription_type: analysis_update
  level: INFO
  message: Image successfully analyzed
  resource:
    id: docker.io/library/alpine:latest
    type: image_tag
    user_id: admin
  source:
    base_url: http://engine-analyzer:8228
    hostid: anchore-quickstart
    servicename: analyzer
  timestamp: '2019-11-17T02:30:43.968476Z'
  type: analyze_image_success
notificationId: b9e7822e-687d-46d6-9c22-67baa8cce0f8
```
