### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#21]
```
category: user
details:
  msg: Think of better errors
id: b63b415f-3b5b-4307-ac08-ee71d8c8ebde
level: ERROR
message: Failed to analyze image
resource:
  id: xyz
  type: image_digest
  user_id: admin
timestamp: '2019-11-21T00:26:27.488181Z'
type: analyze_image_fail
```
