### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#22]
```
category: user
details:
  msg: Think of better errors
id: 7e8bdd4e-a676-4606-88f8-941a99913267
level: ERROR
message: Failed to analyze image
resource:
  id: sha:xyz
  type: image_digest
  user_id: admin
source:
  base_url: null
  hostid: null
  request_id: null
  servicename: null
timestamp: '2019-11-21T00:56:41.277567'
type: analyze_image_fail
```
