### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#23]
```
category: user
details:
  msg: Think of better errors
id: 9529b77e-1123-48d7-abbd-9e42728ef551
level: ERROR
message: Failed to analyze image
resource:
  id: sha:xyz
  type: image_digest
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: analyzer
timestamp: '2019-11-21T19:24:46.086417'
type: analyze_image_fail
```
