### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#24]
```
category: user
details:
  curr_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha:xyz
  last_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha:xyz
  subscription_type: analysis_update
id: 5abae795-cc7d-4eb5-b354-ed533ea7d4bd
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/blah/foo:bar
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: analyzer
timestamp: '2019-11-21T19:39:28.138218'
type: analyze_image_success
```
