### ISSUE TITLE
Anchore recorded active_policy_bundle_content_change event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#25]
```
category: user
details:
  current_policy_bundle_digest: fbfab0e757605f258fb43f62c9cd869c0d8e1f0c7d05adb15bf6ff0156a5db31
  last_policy_bundle_digest: 9f9b4d00af86720ce9adbc8319f813efa25a10edf1ef06dd9d1975cc93600d62
  policy_id: 2c53a13c-1765-11e8-82ef-23527761d060
id: 3f4ad7f8-54c5-433c-be43-94f0a39d2a62
level: INFO
message: Active policy bundle content changed
resource:
  id: null
  type: policy_bundle
  user_id: admin
source:
  base_url: http://engine-catalog:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: catalog
timestamp: '2019-11-21T20:06:51.138860'
type: active_policy_bundle_content_change
```
