### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#27]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a
  subscription_type: analysis_update
id: e4fb6916-8b39-4241-ab0c-433a110ed730
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/nightfurys/test:latest
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-21T21:02:52.667226Z'
type: analyze_image_success
```
