### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#28]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:06888500a6e8fc2e2a06ddf83417b10660d457b1ba1e4a06bdcd427cfd394b31
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:06888500a6e8fc2e2a06ddf83417b10660d457b1ba1e4a06bdcd427cfd394b31
  subscription_type: analysis_update
id: 07d07bd9-5883-4f65-90d1-a1f87f505a18
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/nightfurys/test:latest
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-21T21:31:42.077256Z'
type: analyze_image_success
```
