### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#29]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:be4c352dace07bb1437bf615703afb66fcf4506c633ed26b75baad41d925186e
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:be4c352dace07bb1437bf615703afb66fcf4506c633ed26b75baad41d925186e
  subscription_type: analysis_update
id: a6bf559c-ce50-4f15-b926-450159f3b20d
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/python:latest
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-21T22:07:14.928281Z'
type: analyze_image_success
```
