### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#30]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:06888500a6e8fc2e2a06ddf83417b10660d457b1ba1e4a06bdcd427cfd394b31
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:06888500a6e8fc2e2a06ddf83417b10660d457b1ba1e4a06bdcd427cfd394b31
  subscription_type: analysis_update
id: a9bdd1c3-0a39-4b20-b72f-34ca0d948a83
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/nightfurys/test:latest
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T00:03:37.132302Z'
type: analyze_image_success
```
