### ISSUE TITLE
Anchore recorded active_policy_bundle_id_change event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#33]
```
category: user
details:
  current_policy_bundle_id: a3dcc915-a81e-4ab4-9a48-a5f0a24a1d96
  last_policy_bundle_id: 2c53a13c-1765-11e8-82ef-23527761d060
id: d91a1d5f-3d64-436d-9a9c-de3674dd8b5c
level: INFO
message: Active policy bundle ID changed
resource:
  id: null
  type: policy_bundle
  user_id: admin
source:
  base_url: http://engine-catalog:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: catalog
timestamp: '2019-11-22T00:56:26.198894'
type: active_policy_bundle_id_change
```
