### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#34]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:c034b755cff51640fd10aa13218e2fabee5c77e987c60f2d768cb86634f1776d
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:c034b755cff51640fd10aa13218e2fabee5c77e987c60f2d768cb86634f1776d
  subscription_type: analysis_update
id: b5557cdf-1301-4b98-9d62-4430f325886b
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/anchore/enterprise:latest
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T01:08:56.183786Z'
type: analyze_image_success
```
