### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#35]
```
category: user
details:
  msg: 'Failed to pull image (docker.io/anchore/private_testing@sha256:4f9922f2e141290fe0366ceb8d6e7af88a056793ad9a4351f5b3d43f4305692e) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=false   docker://docker.io/anchore/private_testing@sha256:4f9922f2e141290fe0366ceb8d6e7af88a056793ad9a4351f5b3d43f4305692e oci:/analysis_scratch/56383356-4af0-4e62-bd33-6f5bc1538a2c/raw:image, rc=1, stdout=None, stderr=b''time="2019-11-22T01:14:56Z" level=fatal msg="Error determining manifest MIME type for docker://anchore/private_testing@sha256:4f9922f2e141290fe0366ceb8d6e7af88a056793ad9a4351f5b3d43f4305692e: Error reading manifest sha256:4f9922f2e141290fe0366ceb8d6e7af88a056793ad9a4351f5b3d43f4305692e in docker.io/anchore/private_testing: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n" \n'', error_code=REGISTRY_PERMISSION_DENIED'
id: 6ff5887b-0a76-498e-a1fe-2bbef12bb477
level: ERROR
message: Failed to analyze image
resource:
  id: sha256:4f9922f2e141290fe0366ceb8d6e7af88a056793ad9a4351f5b3d43f4305692e
  type: image_digest
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T01:14:56.197178Z'
type: analyze_image_fail
```
