### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#36]
```
category: user
details:
  msg: 'Failed to pull image (docker.io/nightfurys/test@sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://docker.io/nightfurys/test@sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a oci:/analysis_scratch/ab9a39da-b622-49c1-be71-f7cfc6853a77/raw:image, rc=1, stdout=None, stderr=b''time="2019-11-22T20:07:46Z" level=fatal msg="Error determining manifest MIME type for docker://nightfurys/test@sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a: unable to retrieve auth token: invalid username/password" \n'', error_code=SKOPEO_UNKNOWN_ERROR'
id: f046ea81-08af-4c97-984b-5d371b029c8f
level: ERROR
message: Failed to analyze image
resource:
  id: sha256:9d2b250af5748cf8fb2c7e9a14aab830c251daa3f8f3bc787bd4a3e8c586f39a
  type: image_digest
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T20:07:46.587368Z'
type: analyze_image_fail
```
