### ISSUE TITLE
Anchore recorded analyze_image_fail event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#37]
```
category: user
details:
  msg: 'Failed to pull image (docker.io/nightfurys/test@sha256:4062a9c35943f4eda8d5cd0a53ebe210e49b907b2c3596b1ec4aa010c9828201) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://docker.io/nightfurys/test@sha256:4062a9c35943f4eda8d5cd0a53ebe210e49b907b2c3596b1ec4aa010c9828201 oci:/analysis_scratch/c538bd89-8345-408b-94c2-cb58dabd8fe1/raw:image, rc=1, stdout=None, stderr=b''time="2019-11-22T20:07:56Z" level=fatal msg="Error determining manifest MIME type for docker://nightfurys/test@sha256:4062a9c35943f4eda8d5cd0a53ebe210e49b907b2c3596b1ec4aa010c9828201: unable to retrieve auth token: invalid username/password" \n'', error_code=SKOPEO_UNKNOWN_ERROR'
id: 25d7a37c-566f-4e8f-b6e1-449d7441262a
level: ERROR
message: Failed to analyze image
resource:
  id: sha256:4062a9c35943f4eda8d5cd0a53ebe210e49b907b2c3596b1ec4aa010c9828201
  type: image_digest
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T20:07:56.454938Z'
type: analyze_image_fail
```
