### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#38]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:b3f32cdf17fa5bb8cb9dc32956cf8a27799159f499e44a11ac35b31e0b14158e
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:b3f32cdf17fa5bb8cb9dc32956cf8a27799159f499e44a11ac35b31e0b14158e
  subscription_type: analysis_update
id: a055dd9f-561d-4ab4-b95d-b980903820dd
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:12.13.0-alpine3.9
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:20:16.050550Z'
type: analyze_image_success
```
