### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#39]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:b930ae34213b9bcda4ab598d16159cc2acfd5b26342eff536807d99106f4dd84
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:b930ae34213b9bcda4ab598d16159cc2acfd5b26342eff536807d99106f4dd84
  subscription_type: analysis_update
id: dba0acb5-d65b-44fd-af06-5278fda88879
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:dubnium-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:21:26.223704Z'
type: analyze_image_success
```
