### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#42]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:9d6efa1cc2f6b80134777d62f7553451da9f490e62888fb8b5d39e357132981b
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:9d6efa1cc2f6b80134777d62f7553451da9f490e62888fb8b5d39e357132981b
  subscription_type: analysis_update
id: 85dd39a9-01c1-455c-a096-5eb32459f440
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:8-alpine3.9
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:22:40.981886Z'
type: analyze_image_success
```
