### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#45]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:e820bbb6174b672a8eaf3c08aea105f0e436e4f85f46d973271b0cf73084deb5
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:e820bbb6174b672a8eaf3c08aea105f0e436e4f85f46d973271b0cf73084deb5
  subscription_type: analysis_update
id: 14925fba-66b1-454e-80c9-2a1609a7eef2
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:carbon-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:24:02.125885Z'
type: analyze_image_success
```
