### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#47]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:e820bbb6174b672a8eaf3c08aea105f0e436e4f85f46d973271b0cf73084deb5
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:e820bbb6174b672a8eaf3c08aea105f0e436e4f85f46d973271b0cf73084deb5
  subscription_type: analysis_update
id: 1a22203b-0d7d-4815-a4db-49a4529adbbc
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:8.16-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:24:02.125918Z'
type: analyze_image_success
```
