### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#48]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:ed9b552869870e0b49b73c6e3b8af3da52d20cfc1ea10de3bdb310cc37db77a7
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:ed9b552869870e0b49b73c6e3b8af3da52d20cfc1ea10de3bdb310cc37db77a7
  subscription_type: analysis_update
id: 4b3ba3e5-9d8b-4ca9-8fd1-322971c7e852
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:12.13.1
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:30:18.642642Z'
type: analyze_image_success
```
