### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#49]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:ed9b552869870e0b49b73c6e3b8af3da52d20cfc1ea10de3bdb310cc37db77a7
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:ed9b552869870e0b49b73c6e3b8af3da52d20cfc1ea10de3bdb310cc37db77a7
  subscription_type: analysis_update
id: 579a9e24-580b-4053-b9a1-2aa8512bfb2a
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:12.13.1-stretch
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:30:18.642712Z'
type: analyze_image_success
```
