### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#52]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:ba91769cc479cc07b18b6a03a1c151b2f3833db656591b26fa71c8b747a91069
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:ba91769cc479cc07b18b6a03a1c151b2f3833db656591b26fa71c8b747a91069
  subscription_type: analysis_update
id: bde50554-6882-4875-a5f1-6033dbf57d6f
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:10-alpine3.9
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:31:30.910187Z'
type: analyze_image_success
```
