### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#55]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:212de6a258ca0ad96b96f5b9aa54fd63ffec585514a4f35870723864b63a2a1a
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:212de6a258ca0ad96b96f5b9aa54fd63ffec585514a4f35870723864b63a2a1a
  subscription_type: analysis_update
id: 5f494f8c-3014-494d-9cf7-7a9e4c127e9b
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:lts-alpine3.9
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:32:33.827061Z'
type: analyze_image_success
```
