### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#60]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  subscription_type: analysis_update
id: cfcdbbc1-5f82-4f69-8478-b553c2330768
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:erbium-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:33:38.808911Z'
type: analyze_image_success
```
