### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#62]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  subscription_type: analysis_update
id: a8665db5-726e-4ac8-b051-4807070b1d98
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:lts-alpine
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:33:38.808960Z'
type: analyze_image_success
```
