### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#63]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  subscription_type: analysis_update
id: ae3da175-4eb7-4bec-be93-45f03bf3bd8a
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:current-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:33:38.808978Z'
type: analyze_image_success
```
