### ISSUE TITLE
Anchore recorded analyze_image_success event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#64]
```
category: user
details:
  curr_eval:
    analysis_status: analyzed
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  last_eval:
    analysis_status: analyzing
    annotations: {}
    imageDigest: sha256:6a0fa47a0c87853c53d1403b34c79befef7df04902d4e206cfaf6a43bedce0dd
  subscription_type: analysis_update
id: 931159ea-a2e0-421e-8d06-f07abf58ea8e
level: INFO
message: Image successfully analyzed
resource:
  id: docker.io/library/node:12.13.1-alpine3.10
  type: image_tag
  user_id: admin
source:
  base_url: http://engine-analyzer:8228
  hostid: anchore-quickstart
  servicename: analyzer
timestamp: '2019-11-22T23:33:38.808997Z'
type: analyze_image_success
```
