### ISSUE TITLE
Anchore recorded random_wisdom event

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#8]
```
event:
  category: system
  message: The very ink with which history is written is merely fluid prejudice - Mark Twain
  timestamp: '2019-11-15T22:59:53.365250'
  type: random_wisdom
notificationId: made-up-uuid

```
