### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#89]
```
details:
  msg: The truth is rarely pure and never simple - Oscar Wilde
id: 46b60930e09644d08495bf932d5520eb
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://enterprise-notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2019-12-06T08:03:42.588102'
type: system.test.random_wisdom
```
