### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by nightfurys** [nightfurys/test-repo#90]
```
details:
  msg: Reality is merely an illusion, albeit a very persistent one - Albert Einstein
id: 3980ebafc0be476dbd9aa4cfa75f1f0e
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://enterprise-notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2019-12-06T20:51:22.822005'
type: system.test.random_wisdom
```
